angular.module('webdrilApp')
.factory('BookService', ['$http', 'ENV','$q', function ($http, ENV, $q) {

    return {
      getPage: getPage
    };

  function getPage(start, number) {
  //return $http({
  //    url: ENV.api+ '/books',
  //    method: "GET",
  //    params: params
  //  });
  //};



 var d = {
      "books": [
        {
          "name": "mno\u017en\u00e9 \u010d\u00edslo",
          "description": "",
          "question_lang_id": 1,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 0,
          "user_id": 121,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-27 19:42:46",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "English",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Petra",
          "surname": "Hilmarov\u00e1",
          "login": "petuli"
        },
        {
          "id": 1167,
          "name": "Direkt 1 06 CZ-DE",
          "description": "CZ-DE",
          "question_lang_id": 6,
          "answer_lang_id": 2,
          "level_id": 1,
          "downloaded": 1,
          "user_id": 233,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-03 16:20:48",
          "download": 0,
          "is_shared": 0,
          "dril_category_id": 0,
          "answer_lang_name": "Czech",
          "aquestion_lang_name": "German",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "risio81"
        },
        {
          "id": 1166,
          "name": "Rodina a man\u017eelstvo",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 5,
          "level_id": 2,
          "downloaded": 4,
          "user_id": 234,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-03 15:35:32",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Slovak",
          "level_name": "Elementary - A1 (pokro\u010dil\u00fd za\u010d\u00e1te\u010dn\u00edk \/ fale\u0161n\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Ras\u0165o",
          "surname": "Fatura",
          "login": "Lasturas6496"
        },
        {
          "id": 1165,
          "name": "Maturita Solutions L05",
          "description": "druh\u00fd pokus",
          "question_lang_id": 6,
          "answer_lang_id": 1,
          "level_id": 3,
          "downloaded": 1,
          "user_id": 233,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-03 12:47:30",
          "download": 0,
          "is_shared": 0,
          "dril_category_id": 0,
          "answer_lang_name": "Czech",
          "aquestion_lang_name": "English",
          "level_name": "Pre-Intermediate - A2 (m\u00edrn\u011b pokro\u010dil\u00fd)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "risio81"
        },
        {
          "id": 1164,
          "name": "Maturita Solutions L05",
          "description": "",
          "question_lang_id": 6,
          "answer_lang_id": 1,
          "level_id": 3,
          "downloaded": 0,
          "user_id": 233,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-03 12:45:41",
          "download": 0,
          "is_shared": 0,
          "dril_category_id": 0,
          "answer_lang_name": "Czech",
          "aquestion_lang_name": "English",
          "level_name": "Pre-Intermediate - A2 (m\u00edrn\u011b pokro\u010dil\u00fd)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "risio81"
        },
        {
          "id": 1163,
          "name": "Chemical secret",
          "description": "",
          "question_lang_id": 1,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 4,
          "user_id": 194,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 21:50:07",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "English",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Pavel",
          "surname": "Hrab\u00e1k",
          "login": "hrabi"
        },
        {
          "id": 1162,
          "name": "Honza-cizina 3",
          "description": "",
          "question_lang_id": 1,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 2,
          "user_id": 141,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 21:14:43",
          "download": 0,
          "is_shared": 0,
          "dril_category_id": 0,
          "answer_lang_name": "English",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Jan",
          "surname": "Pavlica",
          "login": "janpavlica"
        },
        {
          "id": 1161,
          "name": "Lekcia 5",
          "description": "",
          "question_lang_id": 4,
          "answer_lang_id": 5,
          "level_id": 1,
          "downloaded": 1,
          "user_id": 229,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 18:40:50",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "Spanish",
          "aquestion_lang_name": "Slovak",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Simona",
          "surname": "Satrova",
          "login": "siminka"
        },
        {
          "id": 1160,
          "name": "Lekcia 4",
          "description": "",
          "question_lang_id": 4,
          "answer_lang_id": 5,
          "level_id": 1,
          "downloaded": 1,
          "user_id": 229,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 18:32:22",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "Spanish",
          "aquestion_lang_name": "Slovak",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "Simona",
          "surname": "Satrova",
          "login": "siminka"
        },
        {
          "id": 1159,
          "name": "St\u00e1ty\/m\u011bsta",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 4,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 17:03:31",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        },
        {
          "id": 1158,
          "name": "Zv\u00ed\u0159ata",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 5,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 16:02:42",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        },
        {
          "id": 1157,
          "name": "W-Fragen",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 4,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 15:01:17",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        },
        {
          "id": 1156,
          "name": "Barvy",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 3,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 13:55:15",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        },
        {
          "id": 1155,
          "name": "\u010c\u00edslovky",
          "description": "\u010d\u00edslovku",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 3,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 13:41:29",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        },
        {
          "id": 1154,
          "name": "\u010c\u00edslovky",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 0,
          "user_id": 0,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 13:41:05",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": null,
          "surname": null,
          "login": null
        },
        {
          "id": 1153,
          "name": "M\u011bs\u00edce, dny,...",
          "description": "",
          "question_lang_id": 2,
          "answer_lang_id": 6,
          "level_id": 1,
          "downloaded": 4,
          "user_id": 230,
          "changed": "2015-02-24 21:59:24",
          "created": "2014-03-02 12:42:22",
          "download": 0,
          "is_shared": 1,
          "dril_category_id": 0,
          "answer_lang_name": "German",
          "aquestion_lang_name": "Czech",
          "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
          "count_of_words": 368,
          "givenname": "",
          "surname": "",
          "login": "Luke"
        }
      ],
      "count": 1013
    };

    return $q(function (resolve, reject) {
      setTimeout(function () {
        console.log(d);
        resolve(d);
      }, 1000);
    });


  }

}]);
