angular.module('webdrilApp')
.factory('BookService', ['$http', 'ENV','$q', function ($http, ENV, $q) {

    return {
      getPage: getPage
    };

  function getPage(start, number) {
  //return $http({
  //    url: ENV.api+ '/books',
  //    method: "GET",
  //    params: params
  //  });
  //};



 var d =  {
      "books": [
      {
        "id": 1163,
        "name": "Chemical secret",
        "description": "",
        "question_lang_id": 1,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 4,
        "user_id": 194,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 21:50:07",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "English",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "Pavel",
        "surname": "Hrab\u00e1k",
        "login": "hrabi"
      },
      {
        "id": 1162,
        "name": "Honza-cizina 3",
        "description": "",
        "question_lang_id": 1,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 2,
        "user_id": 141,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 21:14:43",
        "download": 0,
        "is_shared": 0,
        "dril_category_id": 0,
        "answer_lang_name": "English",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "Jan",
        "surname": "Pavlica",
        "login": "janpavlica"
      },
      {
        "id": 1161,
        "name": "Lekcia 5",
        "description": "",
        "question_lang_id": 4,
        "answer_lang_id": 5,
        "level_id": 1,
        "downloaded": 1,
        "user_id": 229,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 18:40:50",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "Spanish",
        "aquestion_lang_name": "Slovak",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "Simona",
        "surname": "Satrova",
        "login": "siminka"
      },
      {
        "id": 1160,
        "name": "Lekcia 4",
        "description": "",
        "question_lang_id": 4,
        "answer_lang_id": 5,
        "level_id": 1,
        "downloaded": 1,
        "user_id": 229,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 18:32:22",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "Spanish",
        "aquestion_lang_name": "Slovak",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "Simona",
        "surname": "Satrova",
        "login": "siminka"
      },
      {
        "id": 1159,
        "name": "St\u00e1ty\/m\u011bsta",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 4,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 17:03:31",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1158,
        "name": "Zv\u00ed\u0159ata",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 5,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 16:02:42",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1157,
        "name": "W-Fragen",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 4,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 15:01:17",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1156,
        "name": "Barvy",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 3,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 13:55:15",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1155,
        "name": "\u010c\u00edslovky",
        "description": "\u010d\u00edslovku",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 3,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 13:41:29",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1154,
        "name": "\u010c\u00edslovky",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 0,
        "user_id": 0,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 13:41:05",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": null,
        "surname": null,
        "login": null
      },
      {
        "id": 1153,
        "name": "M\u011bs\u00edce, dny,...",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 4,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 12:42:22",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1152,
        "name": "i-a-u",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 2,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 11:56:34",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1151,
        "name": "i-a-o",
        "description": "",
        "question_lang_id": 2,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 3,
        "user_id": 230,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 11:17:15",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "German",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "",
        "surname": "",
        "login": "Luke"
      },
      {
        "id": 1150,
        "name": "New English File",
        "description": "",
        "question_lang_id": 1,
        "answer_lang_id": 6,
        "level_id": 1,
        "downloaded": 2,
        "user_id": 0,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-02 09:03:49",
        "download": 0,
        "is_shared": 1,
        "dril_category_id": 0,
        "answer_lang_name": "English",
        "aquestion_lang_name": "Czech",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": null,
        "surname": null,
        "login": null
      },
      {
        "id": 1149,
        "name": "Lekcia 3",
        "description": "",
        "question_lang_id": 4,
        "answer_lang_id": 5,
        "level_id": 1,
        "downloaded": 1,
        "user_id": 229,
        "changed": "2015-02-24 21:59:24",
        "created": "2014-03-01 13:31:24",
        "download": 0,
        "is_shared": 0,
        "dril_category_id": 0,
        "answer_lang_name": "Spanish",
        "aquestion_lang_name": "Slovak",
        "level_name": "Starter \/ Beginner (\u00fapln\u00fd za\u010d\u00e1te\u010dn\u00edk)",
        "no_of_lectures": 4,
        "no_of_words": "368",
        "givenname": "Simona",
        "surname": "Satrova",
        "login": "siminka"
      }
    ],
      "count": 1013
    };

    return $q(function (resolve, reject) {
      setTimeout(function () {
        console.log(d);
        resolve(d);
      }, 1000);
    });


  }

}]);
